version: '3.8'

services:
  app:
    container_name: springboot_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/meu_banco?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: meu_usuario
      SPRING_DATASOURCE_PASSWORD: minha_senha
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - my_network

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: minha_senha
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysqldata:

networks:
  my_network:
